mymultitools/docs/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        r'^student-ticket-create/(?P<pk>\d+)/$',
        views.StudentTicketCreateView.as_view(),
        name='create_student_ticket',
    ),
    url(
        r'^library-card-create/(?P<pk>\d+)/$',
        views.LibraryCardCreateView.as_view(),
        name='create_library_card',
    ),

    url(
        r'^student-ticket-update/(?P<pk>\d+)/$',
        views.StudentTicketUpdateView.as_view(),
        name='update_student_ticket',
    ),
    url(
        r'^library-card-update/(?P<pk>\d+)/$',
        views.LibraryCardUpdateView.as_view(),
        name='update_library_card',
    ),
    url(
        r'^test$',
        views.StudentTicketCreateTEST.as_view(),
        name='test_docs',
    )
]

mymultitools/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^$',
        views.HomeView.as_view(),
        name='home',
    ),
    url(
        r'^agent_get$',
        views.InstituteAgentGetView.as_view(),
        name='get_agent',
    ),
    url(
        r'^student_get$',
        views.StudentGetView.as_view(),
        name='get_student',
    ),
    url(
        r'^teacher_get$',
        views.TeacherFormGetView.as_view(),
        name='get_teacher',
    )
]

urlpatterns += [
    url(
        r'^institute/(?P<pk>\d+)/$',
        views.InstituteDetailView.as_view(),
        name='institute_detail',
    ),
    url(
        r'^study-group/(?P<pk>\d+)/$',
        views.StudyGroupDetailView.as_view(),
        name='study_group_detail',
    ),
    url(
        r'^student/(?P<pk>\d+)/$',
        views.StudentDetailView.as_view(),
        name='student_detail'
    ),
    url(
        r'^teacher/(?P<pk>\d+)/$',
        views.TeacherDetailView.as_view(),
        name='teacher_detail'
    ),
]

urlpatterns += [
    url(
        r'^student-create/(?P<pk>\d+)/$',
        views.StudentCreateView.as_view(),
        name='create_student',
    ),
    url(
        r'^group-create/(?P<pk>\d+)/$',
        views.StudyGroupCreateView.as_view(),
        name='create_group',
    ),
    url(
        r'^teacher-create/(?P<pk>\d+)/$',
        views.TeacherCreateView.as_view(),
        name='create_teacher',
    ),
    url(
        r'^agent-create/$',
        views.InstituteAgentCreateView.as_view(),
        name='create_agent',
    ),
    url(
        r'^institute-create/$',
        views.InstituteCreateView.as_view(),
        name='create_institute',
    ),
]

mymultitools/docs/models.py
from django.db import models

from users.models import Student, Institute, UserProfile


class DocBase(models.Model):
    student = models.ForeignKey(
        Student,
        verbose_name='Студент',
        on_delete=models.CASCADE,
    )

    institute = models.ForeignKey(
        Institute,
        verbose_name='Учебное заведение',
        on_delete=models.CASCADE,
    )

    code = models.CharField(
        verbose_name='Код документа',
        max_length=50,
    )

    class Meta:
        abstract = True
        unique_together = [['student', 'institute']]


class StudentTicket(DocBase):
    def get_scan_path(instance, filename):
        return './{0}/StudentTicket/{1}'.format(
            instance.student.uuid,
            filename)

    scan = models.ImageField(
        verbose_name='Скан зачетки',
        upload_to=get_scan_path,
        height_field=None,
        width_field=None,
        max_length=None,
        null=True, blank=True,
    )

    def __str__(self):
        return 'Студенческий {0}'.format(self.student)

    class Meta(DocBase.Meta):
        abstract = False


class LibraryCard(DocBase):
    def get_scan_path_front(instance, filename):
        return './{0}/LibraryCard/front_{1}'.format(
            instance.student.uuid,
            filename)

    def get_scan_path_back(instance, filename):
        return './{0}/LibraryCard/back_{1}'.format(
            instance.student.uuid,
            filename)

    scan_front = models.ImageField(
        verbose_name='Скан спереди',
        upload_to=get_scan_path_front,
        height_field=None,
        width_field=None,
        max_length=None,
        null=True, blank=True,
    )

    scan_back = models.ImageField(
        verbose_name='Скан сзади',
        upload_to=get_scan_path_back,
        height_field=None,
        width_field=None,
        max_length=None,
        null=True, blank=True,
    )

    def __str__(self):
        return 'Читательский '.format(self.student)

    class Meta(DocBase.Meta):
        abstract = False


class Note(models.Model):
    owner = models.ForeignKey(
        UserProfile,
        verbose_name='Владелец',
        on_delete=models.CASCADE,
        related_name='notes'
    )
    name = models.CharField(
        'Название',
        max_length=50
    )
    text = models.TextField(
        'Текст',
        max_length=1000,
    )

mymultitools/users/models/institute.py
from django.db import models
from .user import UserProfile

import uuid


class Institute(models.Model):
    name = models.CharField(
        verbose_name='Название учебного заведения',
        max_length=100,
    )

    def __str__(self):
        return self.name


class InstituteAgent(models.Model):
    user_profile = models.ForeignKey(
        UserProfile,
        verbose_name='Профиль',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='institute_agents',
    )
    institute = models.ForeignKey(
        Institute,
        verbose_name='Учебное заведение',
        on_delete=models.CASCADE,
        related_name='institute_agents',
    )
    uuid = models.UUIDField(
        'Индефикатор учетки представителя учебного заведения',
        default=uuid.uuid4,
    )

    def __str__(self):
        return 'Агент {0}'.format(self.institute)

    def get_cls(self):
        return InstituteAgent

mymultitools/users/models/study.py
from django.db import models
from .institute import Institute
from .user import UserProfile

import uuid


class StudyGroup(models.Model):
    institute = models.ForeignKey(
        Institute,
        verbose_name='Учебное заведение',
        on_delete=models.CASCADE,
        related_name='study_groups',
    )
    name = models.CharField(
        'Название группы',
        max_length=20
    )

    def __str__(self):
        return self.name


class Student(models.Model):
    user_profile = models.ForeignKey(
        UserProfile,
        verbose_name='Профиль',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='students',
    )
    study_group = models.ForeignKey(
        StudyGroup,
        verbose_name='Группа',
        on_delete=models.CASCADE,
        related_name='students',
    )
    is_headman = models.BooleanField('Староста', default=False)
    uuid = models.UUIDField(
        'Индефикатор учетки студента',
        default=uuid.uuid4,
    )

    def __str__(self):
        return '[{0}] {1}'.format(
            self.study_group,
            self.user_profile or 'Ничей'
        )

    @property
    def institute(self):
        return self.study_group.institute

mymultitools/users/models/teacher.py
from django.db import models
from .user import UserProfile
from .institute import Institute

import uuid


class Teacher(models.Model):
    user_profile = models.ForeignKey(
        UserProfile,
        verbose_name='Профиль',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='teachers',
    )
    institute = models.ForeignKey(
        Institute,
        verbose_name='Учебное заведение',
        on_delete=models.CASCADE,
        related_name='teachers',
    )
    uuid = models.UUIDField(
        'Индефикатор учетки преподавателя',
        default=uuid.uuid4,
    )

    def __str__(self):
        return '{0} {1}'.format(
            self.user_profile or 'Не назначен',
            self.institute,
        )

mymultitools/users/models/user.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )

    name = models.CharField(
        verbose_name='Имя',
        max_length=30,
    )
    surname = models.CharField(
        verbose_name='Фамилия',
        max_length=30,
    )
    middle_name = models.CharField(
        verbose_name='Отчество',
        max_length=30,
        null=True, blank=True,
    )
    email = models.EmailField(
        max_length=150
    )

    uuid = models.UUIDField(
        default=uuid.uuid4
    )

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            if instance.is_superuser:
                UserProfile.objects.create(user=instance, email='exapmle@mail.ru')
            else:
                UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_userprofile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return '[{0}] {1} {2} {3}'.format(
            self.user.username,
            self.name,
            self.surname,
            self.middle_name,
        )

mymultitools/users/forms/modal_forms.py
from django import forms
from django.shortcuts import get_object_or_404
from bootstrap_modal_forms.forms import BSModalForm

from ..models import Student, Teacher, StudyGroup, Institute


class StudentForm(BSModalForm):
    class Meta:
        model = Student
        fields = ['study_group']
        widgets = {'study_group': forms.HiddenInput}

    def __init__(self, *args, **kwargs):
        study_group = get_object_or_404(
            StudyGroup, pk=kwargs.pop('study_group')
        )
        super().__init__(*args, **kwargs)
        self.fields['study_group'].initial = study_group
        self.fields['study_group'].disabled = True
        self.fields['study_group'].label = ''


class TeacherForm(BSModalForm):
    class Meta:
        model = Teacher
        fields = ['institute']
        widgets = {'institute': forms.HiddenInput}

    def __init__(self, *args, **kwargs):
        institute = get_object_or_404(
            Institute, pk=kwargs.pop('institute')
        )
        super().__init__(*args, **kwargs)
        self.fields['institute'].initial = institute
        self.fields['institute'].disabled = True
        self.fields['institute'].label = ''


class StudyGroupForm(BSModalForm):
    class Meta:
        model = StudyGroup
        fields = ['institute', 'name']
        widgets = {'institute': forms.HiddenInput}

    def __init__(self, *args, **kwargs):
        institute = get_object_or_404(
            Institute, pk=kwargs.pop('institute')
        )
        super().__init__(*args, **kwargs)
        self.fields['institute'].initial = institute
        self.fields['institute'].disabled = True
        self.fields['institute'].label = ''

mymultitools/users/forms/rights.py
from ..models import InstituteAgent, Student, Teacher, Institute

from django import forms
from bootstrap_modal_forms.forms import BSModalForm


class BaseGetForm(BSModalForm):
    get_model = None
    uuid = forms.UUIDField(
        label='Ключ',
        required=True,
        error_messages={'invalid': 'Проверте правильность ключа'}
    )

    class Meta:
        model = None
        fields = ['uuid']

    def clean(self):
        cleaned_data = super().clean()
        uuid = cleaned_data.get('uuid')
        obj = self.get_model.objects.filter(uuid=uuid).first()
        if not obj:
            raise forms.ValidationError('Проверте правильность ключа')
        if obj.user_profile and obj.user_profile != self.request.user.profile:
            raise forms.ValidationError('Этот ключ уже использовали')
        return cleaned_data

    def save(self, commit=True):
        instance = self.get_model.objects.get(uuid=self.cleaned_data['uuid'])
        instance.user_profile = self.request.user.profile
        if commit:
            instance.save()
        return instance


class InstituteAgentGetForm(BaseGetForm):
    get_model = InstituteAgent

    class Meta(BaseGetForm.Meta):
        model = InstituteAgent


class StudentGetForm(BaseGetForm):
    get_model = Student

    class Meta(BaseGetForm.Meta):
        model = Student


class TeacherGetForm(BaseGetForm):
    get_model = Teacher

    class Meta(BaseGetForm.Meta):
        model = Teacher


class InstituteAgentCreateForm(BSModalForm):
    class Meta:
        model = InstituteAgent
        fields = ['institute', 'uuid']


class InstituteCreateForm(BSModalForm):
    class Meta:
        model = Institute
        fields = '__all__'

mymultitools/users/views/modal_views.py
from django.urls import reverse_lazy
from bootstrap_modal_forms import generic

from ..forms import StudentForm, StudyGroupForm, TeacherForm, InstituteCreateForm
from ..models import Institute

class StudentCreateView(generic.BSModalCreateView):
    template_name = 'modal_forms/create_student.html'
    form_class = StudentForm
    success_message = 'Success'

    def get_success_url(self):
        return reverse_lazy(
            'study_group_detail',
            args=(self.object.study_group.pk,)
        )

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs['study_group'] = self.kwargs['pk']
        return kwargs


class StudyGroupCreateView(generic.BSModalCreateView):
    template_name = 'modal_forms/create_study_group.html'
    form_class = StudyGroupForm
    success_message = 'Success'

    def get_success_url(self):
        return reverse_lazy(
            'institute_detail',
            args=(self.object.institute.pk,)
        )

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs['institute'] = self.kwargs['pk']
        return kwargs


class TeacherCreateView(generic.BSModalCreateView):
    template_name = 'modal_forms/create_teacher.html'
    form_class = TeacherForm
    success_message = 'Success'

    def get_success_url(self):
        return reverse_lazy(
            'institute_detail',
            args=(self.object.institute.pk,)
        )

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs['institute'] = self.kwargs['pk']
        return kwargs


class InstituteCreateView(generic.BSModalCreateView):
    template_name = 'modal_form_base.html'
    form_class = InstituteCreateForm
    success_message = 'Success'
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['modal_title'] = 'Добавить уч заведение'
        return context

mymultitools/users/views/rights.py
from django.urls import reverse_lazy
from bootstrap_modal_forms import generic

from ..forms import InstituteAgentGetForm, StudentGetForm, TeacherGetForm, InstituteAgentCreateForm
from ..models import InstituteAgent


class InstituteAgentGetView(generic.BSModalCreateView):
    template_name = 'modal_forms/institute_agent_form.html'
    form_class = InstituteAgentGetForm
    success_message = 'Success'
    success_url = reverse_lazy('home')


class StudentGetView(generic.BSModalCreateView):
    template_name = 'modal_forms/student_form.html'
    form_class = StudentGetForm
    success_message = 'Success'
    success_url = reverse_lazy('home')


class TeacherFormGetView(generic.BSModalCreateView):
    template_name = 'modal_forms/teacher_form.html'
    form_class = TeacherGetForm
    success_message = 'Success'
    success_url = reverse_lazy('home')


class InstituteAgentCreateView(generic.BSModalCreateView):
    template_name = 'modal_form_base.html'
    form_class = InstituteAgentCreateForm
    success_message = 'Success'
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['modal_title'] = 'Добавить представителя'
        return context

mymultitools/users/views/users.py
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

from ..forms import SignUpForm


def signup_view(request):
    form = SignUpForm(request.POST)
    if form.is_valid():
        user = form.save()
        user.refresh_from_db()

        user.profile.name = form.cleaned_data.get('name')
        user.profile.surname = form.cleaned_data.get('surname')
        user.profile.middle_name = form.cleaned_data.get('middle_name')
        user.profile.email = form.cleaned_data.get('email')

        user.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

mymultitools/users/templates/users/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Hello world!</h1>
    <div>
        <a href="{% url 'test_docs' %}">test</a>
        <li>
            {% for institute_agent in institute_agents %}
                <ul><a href="{% url 'institute_detail' pk=institute_agent.institute.pk %}">Представитель {{ institute_agent.institute }}</a> ({{institute_agent.uuid}})</ul>
            {% endfor %}
        </li>
    </div>
{% endblock content %}

mymultitools/users/templates/users/institute_detail.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="col-sm-10 mt-3">
        <h1>Институт {{ institute }}</h1>
        <h3>Список групп</h3>
        <div class="col-sm-6">
            <button class="create-group btn btn-primary" type="button" name="button">Создать группу</button>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">Кольчество студентов</th>
                    </tr>
                </thead>
                <tbody>
                    {% for group in institute.study_groups.all %}
                        <tr>
                            <th scope="row"><a href="{% url 'study_group_detail' pk=group.pk %}">{{ group }}</a></th>
                            <td>{{ group.students.count }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col-sm-6">
            <h3>Список преподавателей</h3>
            <button class="create-teacher btn btn-primary" type="button" name="button">Добавить преподавателя</button>
            <table class="table">
                <tbody>
                    {% for teacher in institute.teachers.all %}
                        <tr>
                            <th scope="row"><a href="{% url 'teacher_detail' pk=teacher.pk %}">{{ teacher }}</a> {% if not teacher.user_profile %}{{teacher.uuid}}{% endif %}</th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

{% block sub_scripts %}
    <script type="text/javascript">
      $(document).ready(function() {
        $(".create-group").modalForm({
          formURL: "{% url 'create_group' pk=institute.pk %}"
        });
      });
      $(document).ready(function() {
        $(".create-teacher").modalForm({
          formURL: "{% url 'create_teacher' pk=institute.pk %}"
        });
      });
    </script>
{% endblock sub_scripts %}

mymultitools/users/templates/users/student_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-sm-10 mt-3">
        <h1>Cтудент {{ student }}</h1>
        {% if student.studentticket_set.first %}
            {% with student.studentticket_set.first as student_ticket %}
                <h3>Студенческий</h3>
                <div>
                    <span>Номер: {{ student_ticket.code }}</span>
                    <img src="{{ student_ticket.scan }}" alt="скан">
                </div>
                <button class="update-student-ticket btn btn-primary" type="button" name="button">Изменить студенческий</button>
            {% endwith %}
        {% else %}
            <button class="create-student-ticket btn btn-primary" type="button" name="button">Добавить студенческий</button>
        {% endif %}
        {% if student.librarycard_set.first %}
            {% with student.librarycard_set.first as library_card %}
                <h3>Читательский</h3>
                <div>
                    <span>Номер: {{ library_card.code }}</span>
                    <img src="{{ library_card.scan_front }}" alt="скан спереди">
                    <img src="{{ library_card.scan_back }}" alt="скан сзади">
                </div>
                <button class="update-library-card btn btn-primary" type="button" name="button">Изменить читательский</button>
            {% endwith %}
        {% else %}
            <button class="create-library-card btn btn-primary" type="button" name="button">Добавить читательский</button>
        {% endif %}
        <h4>Расписания</h4>
        {% with student.study_group as studygroup %}
            {% include 'schedule.html' %}
        {% endwith %}
    </div>
{% endblock content %}


{% block sub_scripts %}
    <script type="text/javascript">
        {% if student.studentticket_set.first %}
            $(document).ready(function() {
                $(".update-student-ticket").modalForm({
                    formURL: "{% url 'update_student_ticket' pk=student.studentticket_set.first.pk %}"
                });
            });
        {% else %}
            $(document).ready(function() {
                $(".create-student-ticket").modalForm({
                    formURL: "{% url 'create_student_ticket' pk=student.pk %}"
                });
            });
        {% endif %}

        {% if student.librarycard_set.first %}
            $(document).ready(function() {
                $(".update-library-card").modalForm({
                    formURL: "{% url 'update_library_card' pk=student.librarycard_set.first.pk %}"
                });
            });
        {% else %}
            $(document).ready(function() {
                $(".create-library-card").modalForm({
                    formURL: "{% url 'create_library_card' pk=student.pk %}"
                });
            });
        {% endif %}
    </script>
{% endblock sub_scripts %}

mymultitools/users/templates/users/study_group_detail.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="col-sm-10 mt-3">
        <h1>Группа {{ studygroup }}</h1>
        <h3>Список группы</h3>
        <button class="create-student btn btn-primary" type="button" name="button">Добавить студента</button>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Имя</th>
                </tr>
            </thead>
            <tbody>
                {% for student in studygroup.students.all %}
                    <tr>
                        <th scope="row"><a href="{% url 'student_detail' pk=student.pk %}">{{ student }}</a> {% if not student.user_profile %}{{ student.uuid }}{% endif %}</th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <h4>Расписания</h4>
        <button class="create-subgroup btn btn-primary" type="button" name="button">Добавить расписание</button>
        {% include 'schedule.html' %}
    </div>
{% endblock content %}

{% block sub_scripts %}
    <script type="text/javascript">
      $(document).ready(function() {
        $(".create-student").modalForm({
          formURL: "{% url 'create_student' pk=studygroup.pk %}"
        });
      });
      $(document).ready(function() {
        $(".create-subgroup").modalForm({
          formURL: "{% url 'create_subgroup'%}?group={{ studygroup.pk }}"
        });
      });
    </script>
{% endblock sub_scripts %}

mymultitools/users/templates/users/teacher_detail.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="col-sm-10 mt-3">
        <h1>Преподаватель {{ teacher }}</h1>
    </div>
{% endblock content %}